name: main
on: push

env:
  PYTHON_VERSION: '3.9'

jobs:
  test-infra:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install requests
          pip install boto3==1.26.137
          pip install botocore==1.29.137
          
          
      - name: test get-function
        run: |
          cd get-function
          python -m pytest -v
          cd ../../
          
      - name: test put-function
        run: |
          cd put-function
          python -m pytest -v
          cd ../../